# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_type', models.CharField(max_length=15)),
                ('hash_sum', models.CharField(max_length=200)),
                ('group', models.IntegerField(default=0)),
                ('operating_sys', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=20)),
                ('ip_addr', models.CharField(max_length=16)),
                ('geolocation', models.CharField(max_length=100)),
                ('last_contact', models.DateTimeField(verbose_name='last_contact')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='run_date')),
                ('group_assigned', models.IntegerField(default=-1)),
            ],
        ),
    ]
