# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot_command',
            old_name='time_completed',
            new_name='completed',
        ),
    ]
