# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='time',
        ),
        migrations.AddField(
            model_name='command',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 3, 23, 35, 182249, tzinfo=utc), verbose_name='end_time'),
        ),
        migrations.AddField(
            model_name='command',
            name='oneshot',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='command',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 3, 23, 35, 182212, tzinfo=utc), verbose_name='start_time'),
        ),
    ]
