# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0002_auto_20170716_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot_command',
            old_name='completed',
            new_name='time_completed',
        ),
    ]
