# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0002_auto_20170516_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='last_contact',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_contact'),
        ),
        migrations.AlterField(
            model_name='command',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='command',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_time'),
        ),
    ]
