# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0003_auto_20170516_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='cmd_txt',
            field=models.TextField(default=''),
        ),
    ]
