# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0004_auto_20170717_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_command',
            name='time_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
