# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0004_command_cmd_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='hash_assigned',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='group_assigned',
            field=models.IntegerField(default=-2, null=True),
        ),
    ]
