# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0005_auto_20170526_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='group_assigned',
            field=models.IntegerField(blank=True, default=-2, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='hash_assigned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
